### ISSUE TITLE
Should ``post-unlink`` be ``pre-unlink``?

### ISSUE THREAD

**Issue by jakevdp** [conda-forge/ipyleaflet-feedstock#3]
Was looking at this recipe to get an idea about jupyter extensions in conda. Comparing to [conda docs](http://conda.pydata.org/docs/building/build-scripts.html), it looks like the ``post-unlink.*`` files here should actually be ``pre-unlink.*``

Let me know if I'm reading things incorrectly!

**Comment by SylvainCorlay** [comment]
Yes it makes sense. We should also update the  recipes for pythreejs, bqplot, widgetsnbextension and nbpresent then!

**Comment by SylvainCorlay** [comment]
We should probably also add a generated recipe in the [widget-cookiecutter](https://github.com/jupyter/widget-cookiecutter) cc @bollwyvl.

**Comment by bollwyvl** [comment]
> looks like the post-unlink.* files here should actually be pre-unlink.*

Yeah, probably! I've probably made this mistake in a number of places... off to the salt mines.

> We should probably also add a generated recipe in the widget-cookiecutter cc @bollwyvl.

Sounds good. However, with the feedstock approach, there are some information theory and practical issues:
- most meta.yml files seem to use jinja, as does cookiecutter... so these will be a little ugly w/r/t escaping
- you really need to have a tag first, usually... so the recipe wouldn't work out of the box... and would have to be copied into a `staged-recipes` PR first.

so it would be something like this:
```shell
conda install -c conda-forge cookiecutter
cookiecutter https://github.com/jupyter/widget-cookiecutter.git
# do some stuff, get some-extension
git clone https://github.com/conda-forge/staged-recipes.git
cp -r some-extension/conda.recipe staged-recipes/some-extension
```
Not that bad. But it would _also_ be nice to be able to:
```shell
conda build some-extension/conda.recipe
```
right off the bat.

Not sure what to do about that.
