### ISSUE TITLE
Why the juterlab post install was removed

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/ipyleaflet-feedstock#76]
@conda-forge/ipyleaflet team, what was the reason for the removal of the post link scripts in #44?

**Comment by rsignell-usgs** [comment]
Removing the post-links puts the burden on all users instead of one provider!

**Comment by jasongrout** [comment]
I think the reason is so that the package can move to a noarch package. We're planning to do the same in widgetsnbextension: https://github.com/conda-forge/widgetsnbextension-feedstock/issues/52

The extension should still automatically install in notebook >=5.3.0, which has been out for over 2 years now. In other words, you shouldn't miss those postlink scripts at all if you have notebook 5.3 or later.

Do you have a notebook version earlier than 5.3.0?

**Comment by jasongrout** [comment]
> The extension should still automatically install in notebook >=5.3.0,

We've moved to the notebook conf.d approach of installing extensions (introduced in notebook 5.3.0), which just involves putting some files in an etc directory and a share directory to install the extension. This is much simpler for package managers to handle, and means that the extension is automatically installed in the wheel package as well.

**Comment by jasongrout** [comment]
I see that the title above is about JupyterLab. To clarify, the postlink scripts never did anything for JupyterLab. They were just about installing the extension in the classic notebook, which has been superseded over two years ago with the conf.d approach.

**Comment by rsignell-usgs** [comment]
Oh, okay, so just user error.  Phew!   I thought we still needed those because I didn't see the post link script!

**Comment by ocefpaf** [comment]
In a way we do for old notebooks. (And I thought we needed for jupyterlab too, glad we don't!)

**Comment by jasongrout** [comment]
Well, to be sure, please confirm that it works as intended. But the intent here is that things work just the same from the user perspective for notebook >=5.3.

**Comment by martinRenou** [comment]
> In a way we do for old notebooks. (And I thought we needed for jupyterlab too, glad we don't!)

For JupyterLab you still need to rebuild it with `jupyter labextension install jupyter-leaflet` (this installs the extension and rebuild JupyterLab).

Though it has been made easier in https://github.com/jupyter-widgets/ipyleaflet/pull/510, once this is released only `jupyter lab build` will be needed.

**Comment by ocefpaf** [comment]
> For JupyterLab you still need to rebuild it with jupyter labextension install jupyter-leaflet (this installs the extension and rebuild JupyterLab).

Ah! Then my concern on this issue is still valid.

> Though it has been made easier in jupyter-widgets/ipyleaflet#510, once this is released only jupyter lab build will be needed.

Good to know. Not sure how that works but anything that makes it easier to the end users is welcome!
